name: PyTest
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.3"

      - name: Install required libraries
        run: |
          pip install -r requirements.txt
      
      - name: Run test suite
        run: |
          pytest -v e2e.py
